project_id = "lnyylkqxaqjwhykwmbib"

[functions.fetch-matches]
verify_jwt = false

[functions.ai-analysis]
verify_jwt = false

[functions.scrape-hltv]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.ai-discover-matches]
verify_jwt = false

[functions.scrape-cs2-matches]
verify_jwt = false

[functions.cs2-matches-api]
verify_jwt = false

[functions.pandascore-matches]
verify_jwt = false

[functions.hltv-odds]
verify_jwt = false
