project_id = "fzweiksnzvevgxtodobs"

[functions.fetch-matches]
verify_jwt = false

[functions.ai-analysis]
verify_jwt = false

[functions.scrape-hltv]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false